name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        run: |
          ssh botuser@176.126.113.21 << 'EOF'
          cd /opt/BotTaskTracker
          git pull origin master
          mvn clean package
          cp target/Bot-Task-Tracker-1.0.0.jar /opt/telegram-bot/Bot-Task-Tracker.jar
          sudo systemctl restart telegram-bot
          EOF
